<?php if (count($this->users)): ?>
<a href="<?php
        echo $this->url(array(
            "controller" => "users",
            "action" => "reset"));
            ?>">Восстановить пароль</a>
    <table>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th>Actions</th>
            <th>Activated</th>
        </tr>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><a href="<?php
        echo $this->url(array(
            "controller" => "users",
            "action" => "view",
            "id" => $user->id));
            ?>"><?php echo $user->username; ?></a>
                </td>
                <td><?php echo $user->email; ?></td>
                <td><a href="<?php
               echo $this->url(array(
                   "controller" => "users",
                   "action" => "edit",
                   "id" => $user->id
               ));
            ?>">Edit</a>
                    <a href="<?php
               echo $this->url(array(
                   "controller" => "users",
                   "action" => "delete",
                   "id" => $user->id
               ));
            ?>">Delete</a>
                </td>
                <td>
                    <?php echo $user->activated; ?>
                </td>
            </tr>

        <?php endforeach; ?>
    </table>
<?php else: ?>
    <p>Пользователей пока нет =-(</p>
    <a href="<?php
    echo $this->url(array(
        "controller" => "users",
        "action" => "add"));
    ?>">Добавить нового пользователя</a>
<?php endif; ?>
